name: truck_booking_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_login_facebook: ^2.0.1
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  images_picker: ^1.2.11
  flutter_otp_text_field: ^1.2.0
  colorful_safe_area: ^1.0.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
